locale: "en-US"
title: "Zhengyang Geng (耿正阳)"
title_separator: "-"
name: "Zhengyang Geng"
description: "PhD Student at CMU"
url: "https://gsunshine.github.io"
baseurl: ""
repository: "Gsunshine/gsunshine.github.io"
future: true
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: America/Los_Angeles

author:
  name: "Zhengyang Geng"
  avatar: "Gsunshine.jpg"
  bio: "CS PhD student at CMU"
  email: "zhengyanggeng AT gmail.com"
  googlescholar: "https://scholar.google.com/citations?user=lNkw3QYAAAAJ"
  github: "Gsunshine"
  twitter: "ZhengyangGeng"

include:
  - .htaccess
  - _pages

exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
